owner: APIcord
repo: status

sites:
  - name: APIcord
    icon: https://apicord.github.io/imgs/apicord.jpeg
    url: https://apidiscord.l64.repl.co

status-website:
  baseUrl: /status
  logoUrl: https://apicord.github.io/imgs/apicon2.png
  favicon: https://apicord.github.io/imgs/apicon2.png
  name: "APIcord Status"
  navbar:
    - title: Web
      href: /
  #theme: night
  themeUrl: https://apicord.github.io/css/status.css
  css: "body{padding:2%;color:white;margin-left:auto;margin-right:auto;}"
  introTitle: '<div style="text-align:center"><h3><a style="color:white" href="https://fosstodon.org/@APIcord/106999534653986122">APIcord has been discontinued</a></h3><hr></div>'
  introMessage: "This website has been archived"

skipDescriptionUpdate: false
