owner: APIcord
repo: status

sites:
  - name: APIcord
    icon: https://apicord.github.io/imgs/apicord.jpeg
    url: https://apidiscord.l64.repl.co

status-website:
  baseUrl: /status
  logoUrl: https://apicord.github.io/imgs/apicon2.png
  name: "APIcord Status"
  navbar:
    - title: Web
      href: /
  #theme: night
  themeUrl: https://apicord.github.io/css/status.css

skipDescriptionUpdate: false
